国际化!

diff --git a/src/scripts/master b/src/scripts/master
--- a/src/scripts/master
+++ b/src/scripts/master
@@ -1,80 +1,203 @@
 #!/bin/sh
 
-#分析命令行参数
-CONSOLE=false
+function find_java() {
+    # Find Java
+    if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
+        javaexe="$JAVA_HOME/bin/java"
+    elif type -p java > /dev/null 2>&1; then
+        javaexe=$(type -p java)
+    elif [[ -x "/usr/bin/java" ]];  then
+        javaexe="/usr/bin/java"
+    else
+        echo "Unable to find Java, Please set JAVA_HOME or put java (>=1.7) in your PATH."
+        exit 1
+    fi
 
-while getopts ci:p:v opt; do
-	case "$opt" in
-		c) CONSOLE=true ;;
-		v) OPTION_VERBOSE=true ;;
-		i) INSTANCE=${OPTARG} ;;
-		p) PROFILE=${OPTARG} ;;
-		\?)
-			echo "Invalid option: -$OPTARG" >&2
-			exit 1
-			;;
-		:)
-			echo "Option -$OPTARG requires an argument." >&2
-			exit 1
-			;;
-	esac
+    if [[ "$javaexe" ]]; then
+        version=$("$javaexe" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+      if [[ "$version" > $JAVA_VERSION ]]; then
+        echo Java version "$version"
+      else
+        echo javaexe=$javaexe
+        echo Java version "$version" is less than required $JAVA_VERSION
+        exit 1
+      fi
+    fi
+}
+
+# ANSI Colors
+function echoRed() { echo $'\e[0;31m'"$1"$'\e[0m'; }
+function echoGreen() { echo $'\e[0;32m'"$1"$'\e[0m'; }
+function echoYellow() { echo $'\e[0;33m'"$1"$'\e[0m'; }
+
+# Utility functions
+function checkPermissions() {
+  touch "$pid_file" &> /dev/null || { echoRed "Operation not permitted (cannot access pid file)"; return 4; }
+}
+
+function isRunning() {
+  ps -p "$1" &> /dev/null
+}
+
+function await_file() {
+  end=$(date +%s)
+  let "end+=10"
+  while [[ ! -s "$1" ]]; do
+    now=$(date +%s)
+    if [[ $now -ge $end ]]; then
+      break
+    fi
+    sleep 1
+  done
+}
+
+# Action functions
+function start() {
+  if [[ -f "$pid_file" ]]; then
+    pid=$(cat "$pid_file")
+    isRunning "$pid" && { echoYellow "Already running [$pid]"; return 0; }
+  fi
+  do_start "$@"
+}
+
+function do_start() {
+  # setsid
+  $command > /dev/null 2>&1 &
+  pid=$!
+  echo "$pid" > "$pid_file"
+  [[ -z $pid ]] && { echoRed "Failed to start"; return 1; }
+  echoGreen "Started [$pid]"
+}
+
+function stop() {
+  [[ -f $pid_file ]] || { echoYellow "Not running (pidfile not found)"; return 0; }
+  pid=$(cat "$pid_file")
+  isRunning "$pid" || { echoYellow "Not running (process ${pid}). Removing stale pid file."; rm -f "$pid_file"; return 0; }
+  do_stop "$pid" "$pid_file"
+}
+
+function do_stop() {
+
+    # First, we will try to trigger a controlled shutdown using
+    # spring-boot-actuator
+    # curl -X POST http://localhost:$APP_PORT/shutdown < /dev/null > /dev/null 2>&1
+
+  kill "$1" &> /dev/null || { echoRed "Unable to kill process $1"; return 1; }
+  for i in $(seq 1 60); do
+    isRunning "$1" || { echoGreen "Stopped [$1]"; rm -f "$2"; return 0; }
+    [[ $i -eq 30 ]] && kill "$1" &> /dev/null
+    sleep 1
+  done
+  echoRed "Unable to kill process $1";
+  return 1;
+}
+
+function restart() {
+  stop && start
+}
+
+function force_reload() {
+  [[ -f $pid_file ]] || { echoRed "Not running (pidfile not found)"; return 7; }
+  pid=$(cat "$pid_file")
+  rm -f "$pid_file"
+  isRunning "$pid" || { echoRed "Not running (process ${pid} not found)"; return 7; }
+  do_stop "$pid" "$pid_file"
+  do_start
+}
+
+function status() {
+  [[ -f "$pid_file" ]] || { echoRed "Not running"; return 3; }
+  pid=$(cat "$pid_file")
+  isRunning "$pid" || { echoRed "Not running (process ${pid} not found)"; return 1; }
+  echoGreen "Running [$pid]"
+  return 0
+}
+
+function run() {
+#  pushd "$(dirname "$jarfile")" > /dev/null
+  $command
+  result=$?
+#  popd > /dev/null
+  return "$result"
+}
+
+
+
+JAVA_VERSION=1.7
+APP_NAME=slider
+MAIN_CLASS=com.laic.slider.SliderApplication
+INSTANCE=0
+
+[[ -n "$DEBUG" ]] && set -x
+[[ -n "$APP_NAME" ]] && identity=$APP_NAME
+PID_FOLDER=/tmp
+
+#分析命令行参数
+while getopts ci:p: opt; do
+    case "$opt" in
+        c) CONSOLE=true ;;
+        i) INSTANCE=${OPTARG} ;;
+        p) PROFILE=${OPTARG} ;;
+        \?)
+            echoRed "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        :)
+            echoRed "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
 done
 shift $(( OPTIND - 1 )) # now do something with $@
 
-if [ -z "$APP_BASE_DIR" ]; then
-    APP_BASE_DIR=`dirname "$0"`
-    APP_BASE_DIR=`( cd "$APP_BASE_DIR" && cd .. && pwd )`
+if [ -z "$APP_HOME" ]; then
+    APP_HOME=$(dirname "$0")
+    APP_HOME=`( cd "$APP_HOME" && cd .. && pwd )`
 fi
-export APP_BASE_DIR
+cd $APP_HOME
 
-cd $APP_BASE_DIR
-
-if [ -z "$JAVA_HOME" -a -z "$JRE_HOME" ]; then
-    echo "Neither the JAVA_HOME nor the JRE_HOME environment variable is"
-    echo "defined. At least one of these environment variable is needed"
-    echo "to run this program"
-    exit 1
-fi
-if [ -z "$JRE_HOME" ]; then
-    JRE_HOME="$JAVA_HOME"
-fi
-_RUNJAVA="$JRE_HOME/bin/java"
-
-JARPATH="$APP_BASE_DIR/lib"
-
-CLASSPATH=
-if [ ! -z "$CLASSPATH" ]; then
-    CLASSPATH="$CLASSPATH"
-fi
+find_java
 
 # 遍历应用程序依赖的jar包，并加入CLASSPATH。
-for jarfile in `ls lib/.`; do
+for jarfile in $(ls lib); do
     CLASSPATH="${CLASSPATH}:lib/$jarfile"
 done
 
-JAVA_OPTS="-Dlogging.config=file:config/logback-spring.xml"
-if ${CONSOLE}; then
-  JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=dev"
-fi
+JAVA_OPTS="-Xmx2048m -Dsun.misc.URLClassPath.disableJarChecking=true -Dlogging.config=file:config/logback-spring.xml"
+[[ -n "${INSTANCE}" ]] && JAVA_OPTS="${JAVA_OPTS} -Dinstance=${INSTANCE}"
+[[ -n "${PROFILE}" ]] && JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=${PROFILE}"
+[[ -n "${CONSOLE}" ]] && JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=dev"
 
-if [ ! -z "${INSTANCE}" ]; then
-    JAVA_OPTS="${JAVA_OPTS} -Dinstance=${INSTANCE}"
-fi
+pid_file=${PID_FOLDER}/${identity}.${INSTANCE}.pid
 
-if [ ! -z "${PROFILE}" ]; then
-	JAVA_OPTS="${JAVA_OPTS} -Dspring.profiles.active=${PROFILE}"
-fi
-
-#LOGGING_CONF="-Dlogfilename=log/$INSTANCE"
-#JAVA_OPTS="-Dlog4j.configuration=file:$DM_BASE_DIR/conf/log4j.xml"
-VM_OPTS=-Xmx2048m
-MAIN_CLASS=com.laic.slider.SliderApplication
-
-if ${CONSOLE}; then
-	eval "$_RUNJAVA $JAVA_OPTS $VM_OPTS -classpath $CLASSPATH $MAIN_CLASS $@"
+# Determine the script mode
+if [ $# -lt 1 ] ; then
+    action=run
 else
-	eval "setsid $_RUNJAVA $JAVA_OPTS $VM_OPTS -classpath $CLASSPATH $MAIN_CLASS $@ > /dev/null 2>&1 &"
+    action="$1"
+    shift
 fi
 
-exit $?
+# Build actual command to execute
+command="$javaexe $JAVA_OPTS -classpath $CLASSPATH $MAIN_CLASS $*"
+
+# Call the appropriate action function
+case ${action} in
+    start)
+      start "$@"; exit $?;;
+    stop)
+      stop "$@"; exit $?;;
+    restart)
+      restart "$@"; exit $?;;
+    force-reload)
+      force_reload "$@"; exit $?;;
+    status)
+      status "$@"; exit $?;;
+    run)
+      run "$@"; exit $?;;
+    *)
+      echo "Usage: $0 {start|stop|restart|force-reload|status|run}"; exit 1;
+esac
+
+exit 0
 
